

DROP TABLE IF EXISTS `flat_cohort_table`;

CREATE TABLE `flat_cohort_table`(
  `id` INT NOT NULL AUTO_INCREMENT ,
  `patient_id` INT(11) DEFAULT NULL ,
  `gender` VARCHAR(45) DEFAULT NULL ,
  `age_in_months` INT DEFAULT NULL ,
  `earliest_start_date` DATE DEFAULT NULL ,
  `hiv_program_state` VARCHAR(45) DEFAULT NULL ,
  `hiv_program_start_date` DATE DEFAULT NULL ,
  `current_tb_status` VARCHAR(255) DEFAULT NULL ,
  `reason_for_starting` VARCHAR(255) DEFAULT NULL ,
  `ever_registered_at_art` VARCHAR(255) DEFAULT NULL ,
  `date_art_last_taken` date DEFAULT NULL,
  `taken_art_in_last_two_months` varchar(255) DEFAULT NULL,
  `patient_pregnant` VARCHAR(255) DEFAULT NULL ,
  `death_date` DATE  DEFAULT NULL ,
  `drug_induced_abdominal_pain` int(11) DEFAULT NULL,
  `drug_induced_anorexia` int(11) DEFAULT NULL,
  `drug_induced_diarrhea` int(11) DEFAULT NULL,
  `drug_induced_jaundice` int(11) DEFAULT NULL,
  `drug_induced_leg_pain_numbness` int(11) DEFAULT NULL,
  `drug_induced_vomiting` int(11) DEFAULT NULL,
  `drug_induced_peripheral_neuropathy` int(11) DEFAULT NULL,
  `drug_induced_hepatitis` int(11) DEFAULT NULL,
  `drug_induced_anemia` int(11) DEFAULT NULL,
  `drug_induced_lactic_acidosis` int(11) DEFAULT NULL,
  `drug_induced_lipodystrophy` int(11) DEFAULT NULL,
  `drug_induced_skin_rash` int(11) DEFAULT NULL,
  `drug_induced_other_symptom` int(11) DEFAULT NULL,
  `drug_induced_fever` int(11) DEFAULT NULL,
  `drug_induced_cough` int(11) DEFAULT NULL,
  `tb_not_suspected` VARCHAR(255) DEFAULT NULL,
  `tb_suspected` VARCHAR(255) DEFAULT NULL,
  `confirmed_tb_not_on_treatment` VARCHAR(255) DEFAULT NULL,
  `confirmed_tb_on_treatment`  VARCHAR(255) DEFAULT NULL,
  `unknown_tb_status`  VARCHAR(255) DEFAULT NULL,
  `extrapulmonary_tuberculosis` VARCHAR(255) DEFAULT NULL ,
  `pulmonary_tuberculosis` VARCHAR(255) DEFAULT NULL ,
  `pulmonary_tuberculosis_last_2_years` VARCHAR(255) DEFAULT NULL ,
  `kaposis_sarcoma` VARCHAR(255) DEFAULT NULL ,
  `what_was_the_patient_adherence_for_this_drug1` varchar(255) DEFAULT NULL,
  `what_was_the_patient_adherence_for_this_drug2` varchar(255) DEFAULT NULL,
  `what_was_the_patient_adherence_for_this_drug3` varchar(255) DEFAULT NULL,
  `what_was_the_patient_adherence_for_this_drug4` varchar(255) DEFAULT NULL,
  `what_was_the_patient_adherence_for_this_drug5` varchar(255) DEFAULT NULL,
	`arv_regimen_type_unknown` varchar(255) DEFAULT NULL,
  `arv_regimen_type_d4T_3TC_NVP` varchar(255) DEFAULT NULL,
  `arv_regimen_type_triomune` varchar(255) DEFAULT NULL,
  `arv_regimen_type_triomune_30` varchar(255) DEFAULT NULL,
  `arv_regimen_type_triomune_40` varchar(255) DEFAULT NULL,
  `arv_regimen_type_AZT_3TC_NVP` varchar(255) DEFAULT NULL,
  `arv_regimen_type_AZT_3TC_LPV_r` varchar(255) DEFAULT NULL,
  `arv_regimen_type_AZT_3TC_EFV` varchar(255) DEFAULT NULL,
  `arv_regimen_type_d4T_3TC_EFV` varchar(255) DEFAULT NULL,
  `arv_regimen_type_TDF_3TC_NVP` varchar(255) DEFAULT NULL,
  `arv_regimen_type_TDF_3TC_EFV` varchar(255) DEFAULT NULL,
  `arv_regimen_type_ABC_3TC_LPV_r` varchar(255) DEFAULT NULL,
  `arv_regimen_type_TDF_3TC_LPV_r` varchar(255) DEFAULT NULL,
  `arv_regimen_type_d4T_3TC_d4T_3TC_NVP` varchar(255) DEFAULT NULL,
  `arv_regimen_type_AZT_3TC_AZT_3TC_NVP` varchar(255) DEFAULT NULL,
  `drug_name1` varchar(255) DEFAULT NULL,
  `drug_name2` varchar(255) DEFAULT NULL,
  `drug_name3` varchar(255) DEFAULT NULL,  
  `drug_name4` varchar(255) DEFAULT NULL,
  `drug_name5` varchar(255) DEFAULT NULL,
  `drug_inventory_id1` int(11) DEFAULT NULL,
  `drug_inventory_id2` int(11) DEFAULT NULL,
  `drug_inventory_id3` int(11) DEFAULT NULL,
  `drug_inventory_id4` int(11) DEFAULT NULL,
  `drug_inventory_id5` int(11) DEFAULT NULL,
  `drug_auto_expire_date1` date DEFAULT NULL,
  `drug_auto_expire_date2` date DEFAULT NULL,
  `drug_auto_expire_date3` date DEFAULT NULL,
  `drug_auto_expire_date4` date DEFAULT NULL,
  `drug_auto_expire_date5` date DEFAULT NULL,
  PRIMARY KEY (`id`) 
  
);
